# Generated by Django 4.2.7 on 2023-11-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_friendrequest_relationship_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='block_sender',
            field=models.BooleanField(default=False),
        ),
    ]
