# Generated by Django 4.2.7 on 2023-11-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_friendrequest_block_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirm', 'confirm')], default='pending', max_length=10, null=True),
        ),
    ]
