# Generated by Django 4.2.7 on 2023-11-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_curriculumvitae_self_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
