# Generated by Django 4.2.7 on 2023-11-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_class_name_customuser_nick_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default=models.CharField(blank=True, max_length=10, null=True, unique=True), max_length=25, verbose_name='User Slug'),
        ),
    ]
