# Generated by Django 4.2.7 on 2023-11-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_education_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='high_light',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='high_light',
            field=models.BooleanField(default=False),
        ),
    ]
