# Generated by Django 4.2.7 on 2023-11-23 10:36

import django.core.validators
from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_award_high_light_alter_publication_high_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='essentialskill',
            name='description',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essentialskill',
            name='order',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='selfdefinedcontent',
            name='content',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfintroduction',
            name='self_introduction',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
