# Generated by Django 4.2.7 on 2023-11-20 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_workexperience_selfintroduction_selfdefinedcontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfintroduction',
            name='id',
        ),
        migrations.AlterField(
            model_name='selfintroduction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
