# Generated by Django 4.2.7 on 2023-11-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profilepagesetting_use_custom_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='description',
            new_name='detail',
        ),
    ]
