# Generated by Django 4.2.7 on 2023-11-28 07:41

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_description_workexperience_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialskill',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfdefinedcontent',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfintroduction',
            name='self_introduction',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='detail',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
