# Generated by Django 4.2.7 on 2023-11-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentsetting_remove_customuser_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='snapchat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter',
        ),
        migrations.AddField(
            model_name='customuser',
            name='calendly',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_scholar',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medium',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orcid',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='patreon',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reddit',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='spotify',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stackoverflow',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='steam',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitch',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='x',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='discord',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='line',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tiktok',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
    ]
