# Generated by Django 4.2.7 on 2023-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customuser_skype_remove_customuser_snapchat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsetting',
            name='degree',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentsetting',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
