# Generated by Django 4.2.7 on 2023-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_privatesetting_dispaly_namev_on_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatesetting',
            name='dispaly_namev_on_network',
        ),
        migrations.AddField(
            model_name='privatesetting',
            name='display_name_on_network',
            field=models.BooleanField(default=False),
        ),
    ]
