# Generated by Django 5.0 on 2023-12-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_studentsetting_degree_and_more'),
        ('accounts', '0014_remove_privatesetting_dispaly_namev_on_network_and_more'),
    ]

    operations = [
    ]
